[colors]
background = "#002F38"
foreground = "#61BFBF"
selection-background = "#153F48"
selection-foreground = "#61BFBF"

tabs = "#4F8684"
tabs-active = "#6A8DA5"
bar = "#4F8684"
split = "#4F8684"
cursor = "#61BFBF"
vi-cursor = "#61BFBF"

search-match-background = "#8B7E6E"
search-match-foreground = "#61BFBF"
search-focused-match-background = "#006E8E"
search-focused-match-foreground = "#61BFBF"

black = "#0B1C1A"
blue = "#7196A8"
cyan = "#4F8684"
green = "#AAC694"
magenta = "#C66F92"
red = "#C07474"
white = "#DEF0F0"
yellow = "#B8A764"

light-black = "#0E181F"
light-blue = "#71B6DE"
light-cyan = "#6A8DA5"
light-foreground = "#61BFBF"
light-green = "#73A084"
light-magenta = "#D372A8"
light-red = "#DC8E8E"
light-white = "#DEF0F0"
light-yellow = "#D8D781"
