theme = "lofoten"

padding-x = 13
padding-y = [13, 13]

line-height = 1.1
confirm-before-quit = false

[panel]
margin = [5]
row-gap = 10
column-gap = 15

[cursor]
shape = "beam"
blinking = true
blinking-interval = 800

[title]
content = "{{ ABSOLUTE_PATH }}"

[window]
width = 1300
height = 1100
mode = "Maximized"
opacity = 1.0
blur = true
decorations = "Disabled"
colorspace = "display-p3"

[fonts]
size = 20
symbol-map = [
  { start = "4E00", end = "9FFF", font-family = "也字工厂淡淡黑大字库" },
  { start = "3400", end = "4DBF", font-family = "也字工厂淡淡黑大字库" },
  { start = "20000", end = "2A6DF", font-family = "尙古黑体SC" }
]
hinting = true
disable-warnings-not-found = false

[fonts.regular]
family = "UbuntuSansMono Nerd Font"
style = "medium"

[fonts.bold]
family = "UbuntuSansMono Nerd Font"
style = "bold"

[fonts.italic]
family = "UbuntuSansMono Nerd Font"
style = "italic"

[navigation]
mode = "Tab"
clickable = false
hide-if-single = false
current-working-directory = true
color-automation = []

[shell]
program = "murex"
args = ["-quiet"]

[bindings]
keys = [
  { key = "q", with = "alt", action = "Quit" },

  { key = "left", with = "control | shift", action = "SelectPrevTab" },
  { key = "right", with = "control | shift", action = "SelectNextTab" },
  { key = "t", with = "control | shift", action = "CreateTab" },
  { key = "w", with = "control | shift", action = "CloseTab" },
  { key = "1", with = "control | shift", action = "SelectTab(0)" },
  { key = "2", with = "control | shift", action = "SelectTab(1)" },
  { key = "3", with = "control | shift", action = "SelectTab(2)" },
  { key = "4", with = "control | shift", action = "SelectTab(3)" },
  { key = "5", with = "control | shift", action = "SelectTab(4)" },
  { key = "6", with = "control | shift", action = "SelectTab(5)" },
  { key = "7", with = "control | shift", action = "SelectTab(6)" },
  { key = "0", with = "control | shift", action = "SelectTab(7)" },

  { key = "t", with = "control | alt", action = "SplitRight" },
  { key = "w", with = "control | alt", action = "CloseSplitOrTab" },
  { key = "left", with = "control | alt", action = "SelectNextSplit" },
  { key = "right", with = "control | alt", action = "SelectPrevSplit" },

  { key = "=", with = "control | shift", action = "IncreaseFontSize" },
  { key = "-", with = "control | shift", action = "DecreaseFontSize" },
  { key = "c", with = "control | shift", action = "Copy" },
  { key = "v", with = "control | shift", action = "Paste" },
]
